apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: nextjs-demo:latest  
          imagePullPolicy: Never  
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: "0.5"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: nextjs
spec:
  selector:
    app: nextjs
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
